### ISSUE TITLE
[문제] 원시 타입과 객체 타입의 차이

### ISSUE THREAD

**Issue by jessi68** [live-small/JsDeepDive_Study#1]

**Comment by wjdrk80** [comment]
원시 값이 변경 불가능함 그러나 객체는 변경 가능함
원시 값을 변수에 할당시 변수에는 실제 값 저장
객체를 변수에 할당하면 변수에는 참조값 저장

**Comment by live-small** [comment]
@wjdrk80 님 의견에 덧붙여, 재할당 시 차이점을 정리해봤습니다. 

**1. 원시타입**
변경할 수 없는 값(불변성). 
원시값을 담은 변수는 재할당을 통해 값을 변경할 수 있음. 
*변수 값 변경시, 메모리 주소값이 변경됨.
*이전 값은 더이상 포인팅하는 변수가 없으니, 가비지컬렉션에 의해 메모리해제됨. 

**2. 객체**
변경할 수 있음. 
*값을 변경해도, 메모리 주소값이 변경되지 않음. 

@jessi68  님의 답변도 궁금해요 !

**Comment by jessi68** [comment]
제가 의도한 것과 같습니다. 변수 값 변경시 불변이기에  새로 할당되어 메모리 주소값이 바뀌는 것이 원시타입이고 변수값만 바뀌고 메모니주소는 그대로인것이 객체타입의 특성입니다.
