### ISSUE TITLE
[토의] Array.prototype.push 와 Array.proptotype.concat 의 용도 차이

### ISSUE THREAD

**Issue by jessi68** [live-small/JsDeepDive_Study#13]
### 질문 
Array.prototype.push 와 Array.proptotype.concat 의 용도 차이는 과연 무엇일까요?

### 상세내용 
 Array.prototype.push 와 Array.proptotype.concat 은 미묘한 차이가 있지만 기능은 비슷합니다. 그렇다면, 어떤 상황에서 전자의 함수인 push 를 쓰는게 적절하고, 어떨때 후자인 concat 함수를 쓰는 것이 적절할까요? 불변성과 연관지어서 생각을 해보면 좋을 것 같습니다.
### 참고
27장

**Comment by live-small** [comment]
**1. 인수 처리차이** 
`push` 받은 인수 그대로를 원본 배열에 추가한다.  --> 원본배열을 변경해, 불변성을 지키지 못한다. 
`concat` 받은 인수가 배열일 때, 배열의 원소만 추출해 새 배열에 추가한다.  --> 새 배열에 값을 할당한 뒤, 반환한다.
*배열 이외는 push와 동일한 처리. 

**2. 반환값의 차이** 
`push` 새롭게 추가된 인수를 반환한다. 
![image](https://user-images.githubusercontent.com/70274947/132131094-5a0ec470-cf78-463c-a908-316d5fee0aba.png)

`concat` 값을 추가한 새 배열을 반환한다. 
*원본배열을 변경하지 않아, 불변성을 지킬 수 있다. 
*하지만, 꼭 꼭 변수로 반환값을 받아줘야한다. 

**3. 언제 뭘 써야할까?**
배열은 객체로, const 키워드로 정의해도 내부 값이 변경됩니다. (내부 값의 주소가 바뀌는 건 아니기 때문에
가능한 변경가능성을 낮추기 위해, `concat` 이용을 우선으로 해야합니다. 
*원본배열을 직접 바꾸는 경우가 흔하진 않지만, 많은 조건을 통과한 뒤 원본배열을 직접 바꿀 때 `push`를 이용.
