### ISSUE TITLE
[문제] 객체의 불변성

### ISSUE THREAD

**Issue by live-small** [live-small/JsDeepDive_Study#16]
### 질문
스프레드 문법을 통해 객체의 불변성을 지킬 수 있습니다. 
이 외에 객체의 불변성을 지킬 수 있는 다른 방법은 뭐가 있을까요? 
또, 불변성을 신경쓰는 것에 대한 생각을 공유해주세요 : ) 

### 관련 챕터 
35장 

### 참고
```javascript 
const order = {id: 1, order: 'Americano', addMilk: true};
const change = {addMilk: false}; 
const newOrder = {...order, ...change }; // output: {id: 1, order: "Americano", addMilk: false}
```

**Comment by jessi68** [comment]
이외에 불변성을 지킬수 있는 방법은 Json.toStringify 를 사용한 후 Json.parse 함수를 한번더 사용하면, 새로 데이터가 만들어지므로 객체의 불변성을 지킬 수 있습니다. 

사실 객체의 불변성을 신경 쓰는 것은 객체의 값이 계속 바뀜으로써 사용자가 코드를 짤때, 실수를 하거다 디버깅을 하기 어렵게 하는 요인이기에 애초에 그런 일이 발생하지 않도록 불변성을 지키면 디버깅이 더 쉬워지기 때문에 불변성을 지키고자 노력하는 것 같습니다.
