### ISSUE TITLE
[문제] 중첩 함수와 콜백 함수의 차이

### ISSUE THREAD

**Issue by jessi68** [live-small/JsDeepDive_Study#5]

**Comment by live-small** [comment]
매개변수로 함수(=콜백함수)를 전달받는 함수를 고차함수라고 알고있습니다. 
고차함수를 구현할 때 중첩함수를 사용한다는 게, 중첩함수를 내포한 콜백함수를 의미하는건가요?

**Comment by jessi68** [comment]
아 책에서 중첩함수의  정의가 함수 내부에 정의된 함수라고 되어있어서 인수로 받은 콜백함수를 인수로 안 받고 함수 내부에 구현 한 것과 인수로 받아서 구현 할 때의 차이를 말한 거였습니다. 좀 애매하게 질문을 했네요. ㅎ

**Comment by Markers** [comment]
고차 함수 : 함수를 인자(argument)로 받거나 함수를 리턴하는 함수를 말한다.

콜백함수 : 매개변수로 넘어온 함수를 콜백함수라고 한다.

중첩함수 : 함수 안에 또다른 함수가 들어가 있는 형태.

콜백함수는 고차 함수의 인자를 넘겨주는 행위로 사용되어지고, 중첩 함수의 정의로만 보면 고차함수와는 크게 상관은 없어보이지만, 나중에 클로져를 통해서 중첩 함수를 리턴값으로 반환하여 내부의 값을 소멸하지 않고 계속 이용할 수 있는 것으로 알고 있습니다.

아직 클로저에 대한 내용을 알지 못해서 검색한 내용으로만으로 답변해드리네요.
